### ISSUE TITLE
Scripts can fail on projects that require git history

### ISSUE THREAD

**Issue by clayburn** [gradle/gradle-enterprise-build-validation-scripts#138]
We've seen some cases where git logic in tasks or build scripts can cause the scripts to fail due to the shallow cloning of the git repository. For example, a git task that searches for the most recent tag on a given branch can fail when the repo is cloned with a depth of 1.

In most cases, the shallow clone works great, so I believe it should remain the default. However, it may be nice to have a flag to grab a full clone in cases where this is an issue.

**Comment by etiennestuder** [comment]
The coming version of the build validation scripts will allow to configure Git options used when cloning the repo. See [here](https://github.com/gradle/gradle-enterprise-build-validation-scripts/issues/166).

//cc @clayburn
