### ISSUE TITLE
Experiment 5 provides incorrect summary for avoided / executed cacheable tasks

### ISSUE THREAD

**Issue by erichaagdev** [gradle/gradle-enterprise-build-validation-scripts#148]
When running experiment 5 (Gradle), I'm seeing an incorrect report for "Avoided cacheable tasks" and "Executed cacheable tasks".

![image](https://user-images.githubusercontent.com/5797900/192579953-2981577e-8130-439e-b111-38c44240c74b.png)

This is different than what is shown in the actual Build Scan results.

![image](https://user-images.githubusercontent.com/5797900/192580054-3b9c5efb-b0fd-48e8-bd9f-3a6c308b835e.png)

As you can see, the validation script summary indicates cacheable tasks were executed, while the Build Scan results indicate the opposite. 

Additional information:
- Using the latest 2.0 release of the validation scripts

**Comment by etiennestuder** [comment]
Thanks for the fix @jthurne , and thanks for raising this, @erichaagdev.
