### ISSUE TITLE
Experiment 5 fails when using GE Build Cache connector due to missing trailing slash

### ISSUE THREAD

**Issue by erichaagdev** [gradle/gradle-enterprise-build-validation-scripts#155]
When running experiment 5 using Gradle Enterprise 2022.3.5, experiment 5 fails due to the build cache URL returned from the Gradle Enterprise API not having a trailing `/`.

![image](https://user-images.githubusercontent.com/5797900/195451803-51760ee2-a220-4074-bd4c-eaa38345f132.png)

**Comment by erichaagdev** [comment]
I tested this by running through the following steps:

1. Downloaded [the latest dev scripts](https://github.com/gradle/gradle-enterprise-build-validation-scripts/releases/download/development-latest/gradle-enterprise-gradle-build-validation-dev.zip)
2. Running experiment 5 for a CI build which remote build cache configured with Gradle Enterprise cache connector (previously this failed during configuration).

![image](https://user-images.githubusercontent.com/5797900/198146434-9f9f0e4a-c606-472f-9e45-c5b7fd636653.png)

**Comment by etiennestuder** [comment]
@erichaagdev Thanks for verifying.

**Comment by erichaagdev** [comment]
I ran through another set of tests to verify the `--remote-build-cache-url` option. 

## Gradle

```shell
./05-validate-remote-build-caching-ci-local.sh \
  -1 'https://ge.solutions-team.gradle.com/s/ehuydjiy5ahce' \
  --remote-build-cache-url 'https://ge.solutions-team.gradle.com/cache'
```

### Before (2.0)

<img width="1723" alt="image" src="https://user-images.githubusercontent.com/5797900/198443965-acba5493-ee99-4ba1-86c0-5e945672cade.png">

### After (dev)

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/5797900/198444432-125f63ac-ff96-463a-8e64-e68d37032496.png">

## Maven

_**Note: A build failure caused by a missing `/` did not occur in v2.0 of the Maven validation scripts. Instead I verified there were no regressions.**_

```
./04-validate-remote-build-caching-ci-local.sh \
  -1 'https://ge.solutions-team.gradle.com/s/ed6a3h7m3swpa' \
  --args '-DskipTests' \
  --remote-build-cache-url 'https://ge.solutions-team.gradle.com/cache'
```

### Before (2.0)

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/5797900/198447639-2627c23c-edcd-43e9-ad51-32d11ca03b78.png">

### After (dev)

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/5797900/198448251-d0d0087b-5501-4634-b1a9-4914f7257328.png">
