### ISSUE TITLE
Links from experiment summary to build scan timeline use most recent query parameter names

### ISSUE THREAD

**Issue by etiennestuder** [gradle/gradle-enterprise-build-validation-scripts#165]
Recently, the query params on the timeline for Maven and Gradle were streamlined.

We should update our links in the experiment summary accordingly.

**Comment by jthurne** [comment]
Do we want to do this globally, or do we want to adjust the links based on the version of GE the user is running?

**Comment by etiennestuder** [comment]
> Do we want to do this globally, or do we want to adjust the links based on the version of GE the user is running?

I would create version-specific links.

**Comment by etiennestuder** [comment]
Fixed for both Gradle and Maven in:
- https://github.com/gradle/gradle-enterprise-build-validation-scripts/commit/7c910efdb48d1865c4b6e6aa01afea55e637c4a5
- https://github.com/gradle/gradle-enterprise-build-validation-scripts/commit/05d6bf218758b439b1ed1f28cfce1a843d5af2d5
