### ISSUE TITLE
Gradle experiment 3 can be run without Build Scan publishing

### ISSUE THREAD

**Issue by erichaagdev** [gradle/gradle-enterprise-build-validation-scripts#170]
We should provide a mechanism to run experiments without Build Scan publishing for cases where the Gradle Enterprise server may not yet be available.

**Comment by etiennestuder** [comment]
@erichaagdev Let's start with exp3 for Gradle. And once we have that fully working, we can do exp1 and exp2 for Gradle, and then exp1-3 for Maven.
