### ISSUE TITLE
Excluded tasks are not taken into consideration

### ISSUE THREAD

**Issue by erichaagdev** [gradle/gradle-enterprise-build-validation-scripts#188]
Experiment 5 of the Gradle validation scripts does not consider tasks which have been excluded using the `-x` Gradle option. In order to better provide a consistent experience, we should add support for this.

Note: This will also require a change to the Gradle Enterprise API as excluded tasks are not returned in the API response.

**Comment by etiennestuder** [comment]
I've asked the engineering team to expose this value in the Enterprise API of GE 2023.1.

**Comment by etiennestuder** [comment]
Closing for now.
