### ISSUE TITLE
Applying build validation scripts changes buildscript classpath ordering of Gradle Enterprise Gradle plugin

### ISSUE THREAD

**Issue by jprinet** [gradle/gradle-enterprise-build-validation-scripts#201]
Context:
- Gradle Enterprise Gradle plugin is applied with an included build
- Local build of experiment 5 is run with the validation scripts

Expected Result:
- Build script classpath is identical in CI and local build

Current Result:
- Gradle Enterprise plugin is in a different place in the build script classpath between CI and local build
- Running the local build manually solves the issue

I have tried to set up a [reproducer](https://github.com/jprinet/gradle-sample-included-build) which loads the GE plugin through an included build, this didn't allow to reproduce the error though.

This issue looks very similar to [this](https://github.com/gradle/gradle/issues/22273)

**Comment by runningcode** [comment]
Using the build init scripts from the Gradle build action in the build validation scripts might improve the situation.

https://github.com/gradle/gradle-build-action/blob/main/src/resources/init-scripts/build-result-capture.init.gradle

**Comment by etiennestuder** [comment]
To clarify: the gold standard is the init script from the TC build scan plugin. There is already a PR from Daz to apply a very similar init script to the validation scrtips. It just has not been reviewed and merged, yet (and likely has some merge conflicts by now).

**Comment by erichaagdev** [comment]
I started a doc for this issue: https://docs.google.com/document/d/1SSr1gWdRLvTmBugFPepWR-LYt1nNQr-652LI6CHCRLo/edit#heading=h.6nb3qkyzldad

**Comment by erichaagdev** [comment]
I am unassigning this from myself as it has been several weeks since I have worked on this and I do not anticipate working on this again any time soon.

**Comment by etiennestuder** [comment]
Given the investigations by @bigdaz, the conclusion is that this issue will no longer exist in the upcoming version of the build validation scripts since there we do not invoke the builds with `--scan` anymore. The culprit is this Gradle Build Tool issue: https://github.com/gradle/gradle/issues/22273
