### ISSUE TITLE
Include before and after build time in experiment summary

### ISSUE THREAD

**Issue by erichaagdev** [gradle/gradle-enterprise-build-validation-scripts#206]
In the experiment summary, we should display the execution time of both builds, including a time delta. 

With this, we could estimate the additional time savings one would get if the executed cacheable tasks had been avoided (best case scenario). 

We could also provide an estimate on the average build time savings (based on our factor taken from experience, as shown in the DPE presentation).

The data we have available to us (the CSV) does not include the build duration. This will have to be retrieved from the Gradle Enterprise API and changes will need to be made to the `build-scan-support-tool` to calculate this.

One final note, this change does have UX considerations. Before jumping into the code, we will need to begin with a design.

**Comment by etiennestuder** [comment]
Once we get to this item, we should also include `exp1-gradle` and at that point also provide `-x` for that experiment, incl. addressing to always read the project name from the build scan data (see also [here](https://github.com/gradle/gradle-enterprise-build-validation-scripts/pull/248#issuecomment-1353907498)).

**Comment by erichaagdev** [comment]
Proposal for how this should look:

```
General
-------
Project:                      java-ordered-properties
Git repo:                     https://github.com/etiennestuder/java-ordered-properties
....


Performance characteristics
---------------------------
Realized build time saving:   From 2min 5s to 1m 3s, 1min 2s saved wall-clock time
Potential build time saving:  From 2min 5s to 47s, 1min 18s saved wall-clock time
Avoided cacheable tasks:      3 tasks, 2min 4s total saved execution time
Executed cacheable tasks:     1 task, 32s total execution time
Executed non-cacheable tasks: 1 task, 0.010s total execution time
Serialization factor:         2.0
```

**Comment by runningcode** [comment]
I like it. For clarity I would propose making the following change:

Realized build time savings:  1min 2s wall-clock time (from 2min 5s to 1m 3s)
Potential build time savings:  1min 18s wall-clock time (from 2min 5s to 47s)

**Comment by erichaagdev** [comment]
I've created a doc that dives a bit deeper into these changes, such as proposed calculations for the new metrics: https://docs.google.com/document/d/11W1D_H3hvl5AUEEBHzqvk6ZMi7dPofVFm7QmxLXp4m4
