### ISSUE TITLE
Cover new build cache access authentication method in wizard and documentation

### ISSUE THREAD

**Issue by etiennestuder** [gradle/gradle-enterprise-build-validation-scripts#212]
For example, see [here](https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/5e44950d5a2b8cb1cdee150d9b8053e7cc85fc36/components/scripts/lib/wizard.sh#L108-L127).

**Comment by erichaagdev** [comment]
This was snuck in with #673 and is available in version [2.7](https://github.com/gradle/gradle-enterprise-build-validation-scripts/releases/tag/v2.7) of the Develocity Build Validation Scripts.

**Gradle**

https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/5a22aff39b59b2bc9f2e2422243047f1b234a375/components/scripts/lib/interactive-mode.sh#L99-L113

**Maven**  

https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/5a22aff39b59b2bc9f2e2422243047f1b234a375/components/scripts/lib/interactive-mode.sh#L140-L155

Closing this issue.
