### ISSUE TITLE
Return an error code if Gradle experiment 1 is not successful

### ISSUE THREAD

**Issue by jprinet** [gradle/gradle-enterprise-build-validation-scripts#225]
## Description
As a follow up to the _fail if not fully cacheable flag_, we could follow the same approach for Gradle experiment 1 (build incrementality assessment), returning an error code if a task is executed on second build

## Purpose
This would be useful when wrapping the scripts in automated processes

**Comment by etiennestuder** [comment]
This cannot be done in practice since there can always be tasks that are never UP-TO-DATE, e.g. a publish task, a database initialization task, etc.
