### ISSUE TITLE
Enhance the command line invocation with different invocation variations

### ISSUE THREAD

**Issue by erichaagdev** [gradle/gradle-enterprise-build-validation-scripts#232]
During a discussion with @jthurne on #229, we talked about several possible enhancements to the "command to repeat the experiment" in both the introduction and summary sections. This issue captures some of those improvements:

- Include command to repeat the experiment in interactive mode
- Include command to run the _next_ experiment in interactive mode

**Comment by etiennestuder** [comment]
It's an intriguing idea to point to the next experiment, but I'm a bit worried the scripts turn into a monster trying to do everything. Thus, for now, I would like to not do this.
