### ISSUE TITLE
Enforce Gradle Enterprise URL is set when using it in the Capture Build Scan URL Maven extension

### ISSUE THREAD

**Issue by jprinet** [gradle/gradle-enterprise-build-validation-scripts#234]
## Context
When running a Maven build with the automated validation scripts, a build scan link is added to filter the build scans related to a given run.

This is done through the [Capture Build Scan URL Maven extension](https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/6ba97dad760344b0df6f37a5355149a07cb968a1/components/capture-build-scan-url-maven-extension/src/main/java/com/gradle/CaptureBuildScansListener.java#L54).

## Issue
We can not necessarily ensure the ordering in which extensions are applied and that can lead to consuming the Gradle Enterprise server URL before it is actually set by the Gradle Enterprise main extension, which in turn leads to a NullPointerException [there](https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/6ba97dad760344b0df6f37a5355149a07cb968a1/components/capture-build-scan-url-maven-extension/src/main/java/com/gradle/CaptureBuildScansListener.java#L61).

## Proposal
Encapsulate the access in a `api.buildFinished` block to ensure the value is set.

**Comment by etiennestuder** [comment]
@jprinet can you create a PR for this, please?

**Comment by jprinet** [comment]
Ready for review
https://github.com/gradle/gradle-enterprise-build-validation-scripts/pull/239
