### ISSUE TITLE
Add shorthand for `--debug` flag and include it in help text

### ISSUE THREAD

**Issue by erichaagdev** [gradle/gradle-enterprise-build-validation-scripts#247]
With #246 we include `--debug` flag in the command to repeat experiment. This is the only flag which is included that does not have a shorthand notation which makes it inconsistent with all other options. We should add a shorthand option for `--debug` (e.g. `-d`).

I would also like to propose we add `--debug` to the help text displayed by `-h`, `--help`, or when invalid options are provided. Both of these changes should be easy enough to address in the same PR.

**Comment by etiennestuder** [comment]
We do not show --debug on purpose. It's not mean for customers. I'd like to not include it for now.
