### ISSUE TITLE
User is not distracted with internals being logged in console

### ISSUE THREAD

**Issue by etiennestuder** [gradle/gradle-enterprise-build-validation-scripts#253]
Let's move where the scan dump is stored to debug level:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/231070/208287750-a6a5cb3e-592a-4a2d-b57d-73a4e147f8bf.png">

**Comment by erichaagdev** [comment]
From @jthurne:

> This is generated by the GE Gradle Plugin / Maven Extension and not the build validation scripts.  We can still move this to debug logging, but we'll need to update those components to do so.

**Comment by etiennestuder** [comment]
Changing the GE plugin is too much work for too little value
