### ISSUE TITLE
Consider releasing to HomeBrew

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle-enterprise-build-validation-scripts#285]
I guess it would be easier to discover, install, and update the scripts from HomeBrew.

For instance:

```
brew install gradle-validation-scripts
```

**Comment by erichaagdev** [comment]
Hey @vlsi! Thank you for the suggestion!

This is not something we are considering at this time. The value gained by distributing to Homebrew does not outweigh the extra overhead required to do so. It also raises the question of why we don't distribute the build validation scripts to other package managers as well. One final thing to consider is that there are two sets of build validation scripts, one for Gradle and another for Maven, with each set containing several individual scripts. 

Installing the scripts is already easy enough and can be done in a single command [as shown in the README](https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/4b9f218e6d70438506dc0a626288a3b17b96390b/Gradle.md#installation). For example, to install the Gradle scripts:

```
curl -s -L -O https://github.com/gradle/gradle-enterprise-build-validation-scripts/releases/download/v2.2.1/gradle-enterprise-gradle-build-validation-2.2.1.zip && unzip -q -o gradle-enterprise-gradle-build-validation-2.2.1.zip
```

Updating the scripts is as easy as removing the installation directory and running the same command used to install them.

**Comment by vlsi** [comment]
> The value gained by distributing to Homebrew does not outweigh the extra overhead required to do so

AFAIK @aalmiray often says https://jreleaser.org/ can make the release to multiple package managers a breeze.

> Installing the scripts is already easy enough

Even though the link is trivial, I it is hard to discover updates.

With brew, I can `brew upgrade`, and it would upgrade all of them.
Even though I consider myself Gradle enthusiast, I am not quite eager to create folders, add them to path manually, etc.

**Comment by erichaagdev** [comment]
> AFAIK @aalmiray often says https://jreleaser.org/ can make the release to multiple package managers a breeze.

Thanks for mentioning this tool! We will keep it in mind if we ever reconsider releasing the Gradle Enterprise build validation scripts to package managers.

> Even though the link is trivial, I it is hard to discover updates.

I understand. While not the same, you can star or watch the repository to be notified of new releases.

> Even though I consider myself Gradle enthusiast, I am not quite eager to create folders, add them to path manually, etc.

To clarify, it's not required to add the scripts to PATH. In fact, they are meant to be invoked directly from the installation directory.

I am going to close this issue for now since this is not something we plan to do in the near future.

Once again, thank you for the suggestion!
