### ISSUE TITLE
Support repeatable command line arguments

### ISSUE THREAD

**Issue by erichaagdev** [gradle/gradle-enterprise-build-validation-scripts#300]
Argbash supports an `ARG_OPTIONAL_REPEATED` argument type which allows a user to repeat an argument more than once. For example:

```shell
./01-validate-incremental-building.sh -t assemble -t check ...
```

This is currently not supported and results in only the last argument being used (i.e. `check`).

It does not make sense for all arguments to be repeatable, but for some it does make sense to allow this, such as `-t`, `-a`, and `-o`. This would make it much easier to read in scripts when one of these arguments becomes very long and a user wants to break it apart. 

See also: #299

**Comment by etiennestuder** [comment]
@erichaagdev is this addressed by https://github.com/gradle/gradle-enterprise-build-validation-scripts/pull/305 ?

**Comment by jthurne** [comment]
We have decided not to do this one because we determined the cost/benefit ratio doesn't make it worthwhile.
