### ISSUE TITLE
Docker is not listed as a requirement for building from source

### ISSUE THREAD

**Issue by erichaagdev** [gradle/gradle-enterprise-build-validation-scripts#359]
It is not mentioned in the README that Docker is a requirement for building from source. By default, Docker is required by the [`com.felipefzdz.gradle.shellcheck`](https://github.com/felipefzdz/gradle-shellcheck-plugin) plugin. The plugin can also be configured to not require Docker, in which case it will download a compatible binary using a configured installer. We should consider this as another possible option.

We have two possible options:

1. Add having Docker running as a requirement to the [Build from source](https://github.com/gradle/gradle-enterprise-build-validation-scripts#build-from-source) section.
2. Configure the `com.felipefzdz.gradle.shellcheck` plugin to not use Docker, and instead use an installer.

**Comment by etiennestuder** [comment]
PR is [here](https://github.com/gradle/gradle-enterprise-build-validation-scripts/pull/360).

**Comment by etiennestuder** [comment]
Fixed.

**Comment by etiennestuder** [comment]
//cc @DPUkyle
