### ISSUE TITLE
Migrate OpenJDK to Temurin

### ISSUE THREAD

**Issue by runningcode** [gradle/gradle-enterprise-build-validation-scripts#394]
We should consider if the following lines of code should be migrated from OpenJDK to Temurin in order to continue to receive security updates.

For more information, see this blog post: https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/

These lines:
https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/main/components/fetch-build-scan-data-cmdline-tool/src/main/openapi/openapi.yaml#L252-L253

as well as:

https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/main/components/fetch-build-scan-data-cmdline-tool/src/main/openapi/openapi.yaml#L348-L349

**Comment by erichaagdev** [comment]
Those lines only serve as an [example](https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/1c9908a7ab1085525854587d621c54d35279c0b7/components/fetch-build-scan-data-cmdline-tool/src/main/openapi/openapi.yaml#L205) of what a response could look like and do not control or influence anything.

That file is also direct copy of the Gradle Enterprise API specification found [in our official documentation](https://docs.gradle.com/enterprise/api-manual/#2022_4) so I don't think we want to change it.

I think we can close this issue.

**Comment by etiennestuder** [comment]
It's not clear to me why references to the openapi yaml are listed in the description when we have GH actions that should be investigated (not saying they need to be changed, but we should find out).

**Comment by erichaagdev** [comment]
Good point. We shouldn't close the issue if we have references to `adopt` in our workflows. The description should be updated though.

**Comment by etiennestuder** [comment]
Let's approach this holistically across all our repos and create issues for each repo once we intend to tackle it.
