### ISSUE TITLE
Catch GE misconfiguration early

### ISSUE THREAD

**Issue by martinbonnin** [gradle/gradle-enterprise-build-validation-scripts#410]
Running the `01-validate-incremental-building.sh` script failed with 

```
A build scan was not published as you have not authenticated with server 'ge.apollographql.com'.
For more information, please see https://gradle.com/help/gradle-authenticating-with-gradle-enterprise.

ERROR: Experiment aborted due to a non-recoverable failure: No Build Scan was published.
```

It'd be nice if this was checked at the beginning of the script to avoid having to rerun the whole build

**Comment by runningcode** [comment]
@martinbonnin thanks for the feedback. We need some additional information to be able to help:
What version of the build validation scripts were you using?
What was the thing that needed to be "checked" at the beginning of the script?

**Comment by martinbonnin** [comment]
> What version of the build validation scripts were you using?

Using version `v2.3.5`

> What was the thing that needed to be "checked" at the beginning of the script?

Woops sorry I forgot some lines in the output. I was thinking of the authentication keys. I've added a few more lines in the original description:

```
A build scan was not published as you have not authenticated with server 'ge.apollographql.com'.
For more information, please see https://gradle.com/help/gradle-authenticating-with-gradle-enterprise.
```

**Comment by etiennestuder** [comment]
@martinbonnin the build scan is published at the end of the build. Thus, we cannot abort the experiment any earlier than when the first build has finished. I recommend that the first time you run the experiment, you use a task that completes quickly, e.g. `assemble`.

**Comment by martinbonnin** [comment]
Fair enough 👍  I ended up using `help` to double check my setup :)

**Comment by etiennestuder** [comment]
I'll close this issue, given we will continue to rely on the build scan plugin and the GE server to determine if build scan publishing is allowed and possible.

**Comment by etiennestuder** [comment]
You beat me to it, Martin :-)
