### ISSUE TITLE
Performance Characteristics only report "unknown"

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle-enterprise-build-validation-scripts#419]
When running the validation scripts in our repo with v2.3.5, the performance characteristics section always reports unknown. Is there anything we could do to understand why?

```
Performance Characteristics
---------------------------
Initial build time:              <unknown>
Build time with instant savings: <unknown>
Serialization factor:            <unknown>
```

The only related log I can find is one higher up, with a similarly opaque message.

```
Fetching Build Scan data for all builds
ERROR: Encountered an unexpected response while fetching build scan <redacted>.
ERROR: Encountered an unexpected response while fetching build scan <redacted>.
Finished fetching Build Scan data for all builds
```

Other context:
- Gradle 8.1.1
- Gradle Enterprise `3.12.6` + server `2022.4.7`
- Same result with both scripts version `2.3.4` and `2.3.5`

**Comment by etiennestuder** [comment]
The scripts display the performance characteristics based on the build scan data fetched via Enterprise API. These calls were not successful, and thus the scripts have no data to display.

I suggest rerunning the experiment with `--debug`. This will print some more details. If we cannot resolve it in this GH thread, please ping us in our shared Slack channel.

**Comment by ZacSweers** [comment]
Should we be adding `--debug` to the input task or to the invocation of the scripts themselves?

**Comment by erichaagdev** [comment]
To the invocation of the scripts themselves. For example:

```
./03-validate-local-build-caching-different-locations.sh --debug ... 
```

**Comment by ZacSweers** [comment]
It looks like it's because we have a two-factor auth layer set up on our self-hosted instance that is interfering with the API requests to load data. Looking more into it on our side, thanks for the tip about --debug 👍
