### ISSUE TITLE
Artifact name for 'Archive receipt' should be configurable

### ISSUE THREAD

**Issue by wbonnefond** [gradle/gradle-enterprise-build-validation-scripts#644]
### Issue:

When running the experiments using a [matrixed workflow](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-a-matrix-for-your-jobs), the `Archvie receipt` step will fail because the artifact name is the same across all matrixed jobs in the workflow. This was a breaking change with the [v4 upload artifact release.](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes)

<img width="1298" alt="Screenshot 2024-08-02 at 10 57 04 AM" src="https://github.com/user-attachments/assets/cd40b5cf-546e-4d50-be2e-bb66548102d0">

### Solution

The artifact name for the `Archive receipt` step for each experiment should be configurable as part of the action

**Comment by erichaagdev** [comment]
Hi, @wbonnefond. Thanks for taking the time to report this. 

Do you actually need full control over the artifact name or would it be acceptable if we could ensure the artifact name was unique across all matrixed runs?
