### ISSUE TITLE
Add an option to reuse the first clean build across different validations

### ISSUE THREAD

**Issue by sergeykad** [gradle/gradle-enterprise-build-validation-scripts#677]
Since every validation script starts by doing a clean not optimized build the total runtime of the scripts can be quite long. In my case it takes hours.
Preserving the result of the first clean unoptimized build and reusing it across validations can save a lot of time.

This can be accomplished for example by running the validation scripts in a Docker container and saving it after the initial build is done. 
It can be done using [docker container commit](https://docs.docker.com/reference/cli/docker/container/commit/) or [docker container export](https://docs.docker.com/reference/cli/docker/container/export/).

**Comment by erichaagdev** [comment]
Hi @sergeykad. Thank you very much for your interest in improving the Develocity Build Validation Scripts.

This is an interesting idea, but there are several reasons we wouldn't want to do this:

1) we don't want the script execution to depend on having Docker installed and running
2) the general use case is re-running the build after modifications

One of the goals of the scripts is to make the experimentation process as straightforward as possible, requiring little interaction from the user. What I suggest to do in your case is to run the scripts in the background while you continue to work on other tasks. If running them locally is too intensive, you could run them on a CI machine. If that is not possible, then you always have the option to do what you suggest manually.

Once you have the initial results available, you should consider running just a subset of a build for any follow-up investigations. This makes the process go much quicker and can also help isolate the problem. Oftentimes, you will have the same cache miss appear across many projects, but is reproducible when running the task from only a single project.

**Comment by sergeykad** [comment]
Hi @erichaagdev ,
Our multi-module project's build process is taking a long time, and even a single script takes close to an hour with 100% CPU usage during this. As you can imagine the computer is hardly usable for the build duration, so we run it on CI machine.

Given the frequent changes and multiple developers working on the project, we need to run the entire suite periodically to check for issues. Therefore, we're looking for ways to reduce the time it requires to run.

**Comment by erichaagdev** [comment]
@sergeykad we have many very large development teams using the scripts regularly.

Are you running each experiment in parallel? Running the experiments in parallel will always be faster than running each experiment sequentially, even if you were to somehow backup and restore the initial project state.

How frequently are you running the scripts in CI? Is this a scheduled process? The typical use case is to run them once per week during off hours. This way the execution time really doesn't matter.
