### ISSUE TITLE
Github actions gradle v2.5.1 directory mismatch

### ISSUE THREAD

**Issue by rifk** [gradle/gradle-enterprise-build-validation-scripts#685]
### Summary

When running the validation scripts using the [github actions for gradle builds v2.5.1](https://github.com/gradle/gradle-enterprise-build-validation-scripts/tree/v2.5.1/.github/actions/gradle) all experiment actions fail because the `download` action is creating a directory called `develocity-gradle-build-validation`, but the `experiment-[1|2|3]` actions are looking for a directory called `gradle-enterprise-gradle-build-validation` and the experiment action ends with error:

```
/__w/_temp/9b415b99-04cf-4c55-8ed5-4def9c7fafa5.sh: line 40: cd: gradle-enterprise-gradle-build-validation: No such file or directory
Error: Process completed with exit code 1.
```

### Investigation

The download action gets the url of the scripts to download [from](https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/35e54aaf1b53abc7c5d8ade5f20a81b087239bcf/.github/actions/gradle/download/action.yml#L23C9-L23C251) 
```
downloadUrl=$(curl "${curlOpts[@]}" https://api.github.com/repos/gradle/gradle-enterprise-build-validation-scripts/releases/latest | jq -c '.assets[] | select(.content_type == "application/zip")' | jq -r .browser_download_url | grep -v maven)
```

This currently gets two urls
```
https://github.com/gradle/gradle-enterprise-build-validation-scripts/releases/download/v2.7.1/develocity-gradle-build-validation-2.7.1.zip
https://github.com/gradle/gradle-enterprise-build-validation-scripts/releases/download/v2.7.1/gradle-enterprise-gradle-build-validation-2.7.1.zip
```

`develocity-gradle-build-validation-2.7.1.zip` contains a dir called `develocity-gradle-build-validation` 
`gradle-enterprise-gradle-build-validation-2.7.1.zip` contains a dir called `gradle-enterprise-gradle-build-validation`

The download action then downloads the zip file passing both URLs to the [curl command](https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/35e54aaf1b53abc7c5d8ade5f20a81b087239bcf/.github/actions/gradle/download/action.yml#L26)
```
curl "${curlOpts[@]}" --output gradle-enterprise-gradle-build-validation.zip $downloadUrl
```
This will download the `develocity-gradle-build-validation-2.7.1.zip` but naming it `gradle-enterprise-gradle-build-validation.zip`. The download action then unzips it, creating a dir called `develocity-gradle-build-validation` with the scripts inside.

When running the experiment-x action after this it tries to [cd to the extracted directory](https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/35e54aaf1b53abc7c5d8ade5f20a81b087239bcf/.github/actions/gradle/experiment-1/action.yml#L85) from the download action
```
cd gradle-enterprise-gradle-build-validation
```

Since the directory doest it exist the action fails.
```
/__w/_temp/9b415b99-04cf-4c55-8ed5-4def9c7fafa5.sh: line 40: cd: gradle-enterprise-gradle-build-validation: No such file or directory
Error: Process completed with exit code 1.
```

Ive only noticed this issue starting at a few weeks ago. It looks like `https://api.github.com/repos/gradle/gradle-enterprise-build-validation-scripts/releases/latest` has updated recently (the `updated_at` fields are all for `2024-11-06`), and that is probably resulting in the download action getting different/wrong URLs. Although I dont know how to confirm this. Maybe the download action should also grep for `gradle-enterprise-gradle-build-validation` or rename the directory after extracting the zip (the workaround Im currently using is adding a step between the download action and experiment actions which renames the directory.

It also seems a little strange that the v2.5.1 action gets v2.7.1 scripts, but im not sure if this is an issue or not.

**Comment by erichaagdev** [comment]
Hi, @rifk. Thanks for taking the time to report this.

Using a tag does not control the version of the Develocity Build Validation Scripts downloaded. The actions will always download the latest version of the scripts.

We don't currently version the actions themselves, though it is something we have recently discussed. Can you try using the `actions-stable` tag and let me know if you still experience the same behavior? For example:

```yaml
- uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/gradle/download@actions-stable
```

**Comment by rifk** [comment]
Hi @erichaagdev 
Thank you for responding so quickly.
The reason Im using the v2.5.1 tag is because Im restricted from using the `actions/upload-artifact@v4` in my GH actions, and have to use `actions/upload-artifact@v3` instead. The `experiment-[1|2|3]` actions include `actions/upload-artifact` and the only way I found I could restrict to `actions/upload-artifact@v3` was by using the `experiment-[1|2|3]@v2.5.1` and not a higher version. Using `download@actions-stable` with `experiment-[1|2|3]@v2.5.1` has the same issue.

I just had another look at the download actions. v2.5.1 uses `grep -v maven` when picking the zip to download. v2.7.1 (and actions-stable) has `grep develocity-gradle`, which is explicitly getting the `develocity` scripts instead of the `gradle-enterprise` scripts.
Should v2.5 be using `grep gradle-enterprise-gradle`?

**Comment by erichaagdev** [comment]
Thanks for the additional context.

> Should v2.5 be using grep `gradle-enterprise-gradle`?

No, because at the time of the Develocity Build Validation Scripts 2.5 release, there were no Develocity distributions, so we did not have to be so specific with the filter in the actions.

The only version of the actions we support is whatever revision the `actions-stable` tag points to. To be clear, the `2.5` tag does not refer to the actions, it refers to the scripts. You can't use `download@2.5` and expect it to work.

If you are restricted to using `actions/upload-artifact@v3`, then there isn't much that can be done on our end because we aren't going to downgrade the version from `v4`. Your best bet is to fork the repository so you can configure the actions according to your requirements.

**Comment by rifk** [comment]
Thank you for clarifying this @erichaagdev . Ill close the issue as there nothing that can be done.

**Comment by erichaagdev** [comment]
Sure thing. Thanks for the understanding.

As mentioned earlier, we have plans to discuss how to properly version / tag these actions. That would resolve issues like this in the future.
